{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "8QlPePe0MDdE"
      },
      "outputs": [],
      "source": [
        "import firebase_admin\n",
        "from firebase_admin import credentials, db\n",
        "from google.oauth2 import service_account\n",
        "from googleapiclient.discovery import build\n",
        "import time\n",
        "from googleapiclient.errors import HttpError\n",
        "\n",
        "# Firebase アプリ初期化\n",
        "if not firebase_admin._apps:\n",
        "    cred = credentials.Certificate('/content/test-51ebc-firebase-adminsdk-t5g9u-d35ff54294.json')\n",
        "    firebase_admin.initialize_app(cred, {\n",
        "        'databaseURL': 'https://test-51ebc-default-rtdb.firebaseio.com/'\n",
        "    })\n",
        "\n",
        "# データ取得\n",
        "data = db.reference().get()\n",
        "print(data)\n",
        "\n",
        "# Google Sheets APIのサービス初期化\n",
        "SCOPES = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']\n",
        "SERVICE_ACCOUNT_FILE = '/content/basic-advantage-438901-v1-9feb6c0f54b1.json'\n",
        "\n",
        "# サービスアカウントから資格情報取得\n",
        "creds = service_account.Credentials.from_service_account_file(\n",
        "    SERVICE_ACCOUNT_FILE, scopes=SCOPES\n",
        ")\n",
        "\n",
        "# Google SheetsとDriveのサービスを作成\n",
        "sheets_service = build('sheets', 'v4', credentials=creds)\n",
        "drive_service = build('drive', 'v3', credentials=creds)\n",
        "\n",
        "def create_spreadsheet():\n",
        "    # スプレッドシートを作成\n",
        "    spreadsheet = {\n",
        "        'properties': {'title': 'New Spreadsheet'}\n",
        "    }\n",
        "    spreadsheet = sheets_service.spreadsheets().create(body=spreadsheet, fields='spreadsheetId').execute()\n",
        "    sheet_id = spreadsheet.get('spreadsheetId')\n",
        "    print(f'Spreadsheet ID: {sheet_id}')\n",
        "\n",
        "    # データをスプレッドシートに追加\n",
        "    # Firebaseのデータ構造に合わせて値を調整\n",
        "    values = []\n",
        "    # ヘッダー行を追加\n",
        "    headers = ['student_id', 'start', 'finish']\n",
        "    values.append(headers)\n",
        "\n",
        "    # データ行を追加\n",
        "    for student_id, student_data in data['Students'].items():  # Assuming 'Students' is the key\n",
        "        row = [student_id, student_data['start'], student_data['finish']]\n",
        "        values.append(row)\n",
        "\n",
        "    body = {'values': values}\n",
        "    sheets_service.spreadsheets().values().update(\n",
        "        spreadsheetId=sheet_id,\n",
        "        range='Sheet1!A1',\n",
        "        valueInputOption='RAW',\n",
        "        body=body\n",
        "    ).execute()\n",
        "\n",
        "    # Google Driveでの共有設定 with exponential backoff\n",
        "    permission = {\n",
        "        'type': 'user',\n",
        "        'role': 'reader',\n",
        "        'emailAddress': 'e19139@denki.numazu-ct.ac.jp'\n",
        "    }\n",
        "\n",
        "    retries = 0\n",
        "    max_retries = 3\n",
        "    wait_time = 1\n",
        "\n",
        "    while retries < max_retries:\n",
        "        try:\n",
        "            drive_service.permissions().create(fileId=sheet_id, body=permission).execute()\n",
        "            print(f'Spreadsheet shared with e19139@denki.numazu-ct.ac.jp with ID: {sheet_id}')\n",
        "            break\n",
        "        except HttpError as error:\n",
        "            if error.resp.status == 403 and \"sharingRateLimitExceeded\" in str(error):\n",
        "                print(f\"Rate limit exceeded. Retrying in {wait_time} seconds...\")\n",
        "                time.sleep(wait_time)\n",
        "                wait_time *= 2\n",
        "                retries += 1\n",
        "            else:\n",
        "                raise\n",
        "    else:\n",
        "        print(\"Failed to share spreadsheet after multiple retries.\")\n",
        "\n",
        "# スプレッドシートを作成して共有\n",
        "create_spreadsheet()"
      ]
    }
  ]
}