name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Prepare Service Account Keys
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        echo "$GCP_SERVICE_ACCOUNT" > /tmp/gcp_service_account.json

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_service_account.json
      run: python sheet.py
