name: Update Google Sheet

on:
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client firebase-admin

    - name: Set up credentials
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        echo "$GOOGLE_CREDENTIALS" > /tmp/gcp_service_account.json

    - name: Run script
      run: |
        python write_schedule.py
