name: Update Google Sheet

on:
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client firebase-admin

    - name: Run script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        echo "$GCP_SERVICE_ACCOUNT" > /tmp/gcp_service_account.json

        python write_schedule.py
