name: Run Firebase and GCP Tasks

on:
  schedule:
    - cron: '25 10 * * *'  # 時に実行
  workflow_dispatch:    # 手動実行用のトリガー
jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage firebase-admin

    - name: Configure Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase_service_account.json

    - name: Configure Google Cloud
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo "$GCP_SERVICE_ACCOUNT" > /tmp/gcp_service_account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_service_account.json

    - name: Run Script
      run: |
        # Replace with your script that uses Firebase and GCP
        python Untitled1.py
