name: Run Colab Notebook

on:
  schedule:
    - cron: '12 0 * * *'  # 毎日12時に実行（JSTの場合は9時）

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Run Notebook
      run: |
        jupyter nbconvert --to notebook --execute Untitled1.ipynb --output result.ipynb
