name: Write Attendance

on: 
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin gspread oauth2client

    - name: Set up Firebase and Google credentials
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        echo "$GCP_SERVICE_ACCOUNT" > /tmp/gcp_service_account.json

    - name: Run script
      run: python test2.py
