name: Run Firebase and GCP Tasks

on: 
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase_service_account.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase_service_account.json

    - name: Run Script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase_service_account.json
      run: |
        python write_data.py
